/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaedteRouteImport } from './routes/staedte'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LeistungenRouteImport } from './routes/leistungen'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as AgbRouteImport } from './routes/agb'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeistungenHaushaltsaufloesungRouteImport } from './routes/leistungen.haushaltsaufloesung'
import { Route as EntruempelungStadtRouteImport } from './routes/entruempelung.$stadt'

const StaedteRoute = StaedteRouteImport.update({
  id: '/staedte',
  path: '/staedte',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenRoute = LeistungenRouteImport.update({
  id: '/leistungen',
  path: '/leistungen',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const AgbRoute = AgbRouteImport.update({
  id: '/agb',
  path: '/agb',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenHaushaltsaufloesungRoute =
  LeistungenHaushaltsaufloesungRouteImport.update({
    id: '/haushaltsaufloesung',
    path: '/haushaltsaufloesung',
    getParentRoute: () => LeistungenRoute,
  } as any)
const EntruempelungStadtRoute = EntruempelungStadtRouteImport.update({
  id: '/entruempelung/$stadt',
  path: '/entruempelung/$stadt',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/leistungen': typeof LeistungenRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staedte': typeof StaedteRoute
  '/entruempelung/$stadt': typeof EntruempelungStadtRoute
  '/leistungen/haushaltsaufloesung': typeof LeistungenHaushaltsaufloesungRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/leistungen': typeof LeistungenRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staedte': typeof StaedteRoute
  '/entruempelung/$stadt': typeof EntruempelungStadtRoute
  '/leistungen/haushaltsaufloesung': typeof LeistungenHaushaltsaufloesungRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/leistungen': typeof LeistungenRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staedte': typeof StaedteRoute
  '/entruempelung/$stadt': typeof EntruempelungStadtRoute
  '/leistungen/haushaltsaufloesung': typeof LeistungenHaushaltsaufloesungRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agb'
    | '/datenschutz'
    | '/impressum'
    | '/leistungen'
    | '/sitemap.xml'
    | '/staedte'
    | '/entruempelung/$stadt'
    | '/leistungen/haushaltsaufloesung'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agb'
    | '/datenschutz'
    | '/impressum'
    | '/leistungen'
    | '/sitemap.xml'
    | '/staedte'
    | '/entruempelung/$stadt'
    | '/leistungen/haushaltsaufloesung'
  id:
    | '__root__'
    | '/'
    | '/agb'
    | '/datenschutz'
    | '/impressum'
    | '/leistungen'
    | '/sitemap.xml'
    | '/staedte'
    | '/entruempelung/$stadt'
    | '/leistungen/haushaltsaufloesung'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgbRoute: typeof AgbRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  LeistungenRoute: typeof LeistungenRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StaedteRoute: typeof StaedteRoute
  EntruempelungStadtRoute: typeof EntruempelungStadtRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staedte': {
      id: '/staedte'
      path: '/staedte'
      fullPath: '/staedte'
      preLoaderRoute: typeof StaedteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen': {
      id: '/leistungen'
      path: '/leistungen'
      fullPath: '/leistungen'
      preLoaderRoute: typeof LeistungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agb': {
      id: '/agb'
      path: '/agb'
      fullPath: '/agb'
      preLoaderRoute: typeof AgbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen/haushaltsaufloesung': {
      id: '/leistungen/haushaltsaufloesung'
      path: '/haushaltsaufloesung'
      fullPath: '/leistungen/haushaltsaufloesung'
      preLoaderRoute: typeof LeistungenHaushaltsaufloesungRouteImport
      parentRoute: typeof LeistungenRoute
    }
    '/entruempelung/$stadt': {
      id: '/entruempelung/$stadt'
      path: '/entruempelung/$stadt'
      fullPath: '/entruempelung/$stadt'
      preLoaderRoute: typeof EntruempelungStadtRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LeistungenRouteChildren {
  LeistungenHaushaltsaufloesungRoute: typeof LeistungenHaushaltsaufloesungRoute
}

const LeistungenRouteChildren: LeistungenRouteChildren = {
  LeistungenHaushaltsaufloesungRoute: LeistungenHaushaltsaufloesungRoute,
}

const LeistungenRouteWithChildren = LeistungenRoute._addFileChildren(
  LeistungenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgbRoute: AgbRoute,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  LeistungenRoute: LeistungenRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StaedteRoute: StaedteRoute,
  EntruempelungStadtRoute: EntruempelungStadtRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
